# Generated by Django 3.2.2 on 2022-03-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_auto_20210908_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='index',
            field=models.PositiveIntegerField(default=0, help_text='Order in which the activity types will be displayed', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='historicalactivitycategory',
            name='index',
            field=models.PositiveIntegerField(default=0, help_text='Order in which the activity types will be displayed', verbose_name='Order'),
        ),
    ]


