# Generated by Django 3.2.2 on 2022-08-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_auto_20220310_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'ordering': ['index'], 'verbose_name_plural': 'Activity Categories'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.CharField(default='Event Title (Optionnal)', help_text='Event title which will override the Activity name', max_length=100, verbose_name='Event title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='event_title',
            field=models.CharField(default='Event Title (Optionnal)', help_text='Event title which will override the Activity name', max_length=100, verbose_name='Event title'),
            preserve_default=False,
        ),
    ]
